pipeline {
    agent {
        docker {
            image 'jibin321/maven-docker-agent:v2'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                sh 'echo "Checkout passed"'
                // git branch: 'main', url: 'https://github.com/user/repo.git'
            }
        }

        stage('Build and Test') {
            steps {
                sh 'ls -ltr'

                sh '''
                    cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
                    mvn clean package
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app

                        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar \
                        -Dsonar.projectKey=my-ec2-project \
                        -Dsonar.projectName="Spring Boot App" \
                        -Dsonar.host.url=$SONAR_HOST_URL
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {
            environment {
                DOCKER_IMAGE = "ligha/spring-boot-app:${BUILD_NUMBER}"
            }

            steps {
                script {

                    sh 'docker build -t ${DOCKER_IMAGE} java-maven-sonar-argocd-helm-k8s/spring-boot-app'

                    def dockerImage = docker.image("${DOCKER_IMAGE}")

                    docker.withRegistry(
                        'https://index.docker.io/v1/',
                        'docker-cred'
                    ) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Update Deployment File') {
            environment {
                GIT_REPO_NAME = "java-maven-sonar-argocd"
                GIT_USER_NAME = "lighacu"
            }

            steps {
                withCredentials([
                    string(
                        credentialsId: 'github',
                        variable: 'GITHUB_TOKEN'
                    )
                ]) {

                    sh '''
                        git config user.email "lighacu@gmail.com"
                        git config user.name "${GIT_USER_NAME}"

                        sed -i "s|image: .*|image: ligha/spring-boot-app:${BUILD_NUMBER}|g" spring-boot-app-manifests/deployment.yml

                        git add spring-boot-app-manifests/deployment.yml

                        git commit -m "Update Spring Boot image tag to ${BUILD_NUMBER} [skip ci]" || echo "No changes to commit"

                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                    '''
                }
            }
        }
    }
}
